### ISSUE TITLE
Error bin/magento m2bp:critical-css:generate

### ISSUE THREAD

**Issue by EvasBa** [m2-boilerplate/Module-Critical-CSS#13]
Hey,

I am facing this problem:

In Process.php line 256:

  The command "'critical' '--version'" failed.

  Exit Code: 127(Command not found)

  Working directory: /home/admin/web/elektra.lt/public_html

  Output:
  ================

  Error Output:
  ================
  sh: 1: exec: critical: not found

**Comment by thampe** [comment]
Hi,

did you install the crictial npm module: https://github.com/addyosmani/critical#install ?

**Comment by marvinhinz** [comment]
You need to configure the path to critical in the backend. To resolve the path, enter "which critical" in a commandline that can find critical.

**Comment by marvinhinz** [comment]
The command disables the critical path setting, clears the cache and then begins to collect it, because otherwise the async css will not be seen by critical. After the collection is done, the critical path setting will be reactivated and the cache gets cleared.

**Comment by sharjilk** [comment]
I still have this error on `bin/magento m2bp:critical-css:generate`

<img width="363" alt="Screenshot 2022-05-26 at 3 35 38 PM" src="https://user-images.githubusercontent.com/16533463/170480320-c4b3ee7e-81a5-4d21-8094-4d923f0e9ac7.png">

Critical npm package is also installed correctly but `which critical` is giving nothing

**Comment by marvinhinz** [comment]
@sharjilk then your critical executable is not within your PATH, did you install it global or local?

**Comment by sharjilk** [comment]
@marvinhinz 
I installed critical locally and added executable path in admin.
<img width="1036" alt="1" src="https://user-images.githubusercontent.com/16533463/170648023-31af2f17-ed31-40c3-b512-e6d8656a1f49.png">

When I am running `bin/magento m2bp:critical-css:generate` I don't see critical-cc generated inside var directory.

<img width="1415" alt="2" src="https://user-images.githubusercontent.com/16533463/170648196-ce3af041-89ed-42ef-a793-9a9b00d75a39.png">

**Comment by marvinhinz** [comment]
@sharjilk 
![image](https://user-images.githubusercontent.com/35603466/170663149-bb86df18-1cc3-476b-99f0-16c6a525905f.png)
there is your error, you need to install the needed library

**Comment by julianne49** [comment]
Hello I am a newbie to critical/critical path css & am having a difficult time getting it set up. I am using Magento 2.4.4. Critical is installed locally & the binary path set to: node_modules/critical/cli. When I run: bin/magento m2bp:critical-css:generate. I get the following error: 

The command "'node_modules/critical/cli.js' '--version'" failed.

  Exit Code: 1(General error)

  Working directory: /home/public_html/.....

  Output:
  ================


  Error Output:
  ================
  /home/public_html/node_modules/critical/cli.js:2
  import os from 'node:os';
         ^^

  SyntaxError: Unexpected identifier
      at Module._compile (internal/modules/cjs/loader.js:872:18)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
      at Module.load (internal/modules/cjs/loader.js:790:32)
      at Function.Module._load (internal/modules/cjs/loader.js:703:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
      at internal/main/run_main_module.js:17:11

Any help would be greatly appreciated.

**Comment by julianne49** [comment]
Hello again. I was able to get this set up & some what working.  I can now run: "bin/magento m2bp:critical-css:generate" without any of the above issues. However, now when I try to generate css - it seems to run but with different errors &not create a critiacl css. Here is some of the outpute when trying to generate css: "Error Output: ================    Error: Failed to launch the browser process!    /home/julianne49/public_html/example.com/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory      TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md    

Anybody with any clue as to how to fix this - please don't hesitate.

Thank you......

**Comment by sandeep570** [comment]
> @marvinhinz I installed critical locally and added executable path in admin. <img alt="1" width="1036" src="https://user-images.githubusercontent.com/16533463/170648023-31af2f17-ed31-40c3-b512-e6d8656a1f49.png">
> 
> When I am running `bin/magento m2bp:critical-css:generate` I don't see critical-cc generated inside var directory.
> 
> <img alt="2" width="1415" src="https://user-images.githubusercontent.com/16533463/170648196-ce3af041-89ed-42ef-a793-9a9b00d75a39.png">

Any solution on this ??
@marvinhinz  @sharjilk
